[package]
name = "raspi-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
image = "0.25.6"
log = "0.4.27"
ndarray = "0.16.1"
pretty_env_logger = "0.5.0"
ureq = "3.1.0"
warn = "0.2.2"
